name: Playwright Tests
on:
  schedule:
    - cron: "05 05 * * 5"
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: start SearXNG
      run: docker run --rm -d -p 8888:8080 searxng/searxng
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright
      run: npm run install
    - name: Run Playwright tests
      run: npm run test
    - name: Generate report
      run: |
        npm run report
        echo "dev.searxng.org" > allure-report/CNAME
    - name: Deploy to the report branch
      uses: JamesIves/github-pages-deploy-action@v4.7.2
      with:
        branch: report
        folder: allure-report
        single-commit: true
        clean: true
