name: Playwright Tests
on:
  schedule:
    - cron: "05 05 * * 5"
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: start SearXNG
      run: docker run --rm -d -p 8888:8080 searxng/searxng
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright
      run: npm run install
    - name: Run Playwright tests
      run: npm run test
    - name: Generate report
      run: |
        npm run report
        echo "dev.searxng.org" > allure-report/CNAME
    - name: Commit built files to the playwright-report branch
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: report
        FOLDER: allure-report
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
