name: Playwright Tests
on:
  schedule:
    - cron: "05 05 * * 5"
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: start SearXNG
      run: docker run --rm -d -p 8888:8080 searxng/searxng
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: | 
        npx playwright test --reporter=line,experimental-allure-playwright
        npx allure generate ./allure-results --clean
        node attachment_browser/create_json.js
        cp attachment_browser/attachment_browser.html allure-report
    - name: Commit built files to the playwright-report branch
      if: always()
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: report
        FOLDER: allure-report
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
